name: Build and deploy

on:
  push:
    paths:
      - 'package.json'
  pull_request:
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Closure Compiler
        run: npm install google-closure-compiler
      - name: Build
        run: npm run build
      - name: Publish to npm
        if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
